# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
env:
   variables:
     PROJECT: WebAWSCoreApplication
     DOTNET_CORE_RUNTIME: 3.1

phases:   
  install:
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish ./${PROJECT}/${PROJECT}.csproj -o ./staging/app
      - cp ./aws-windows-deployment-manifest.json ./staging/.

artifacts:
  files:
    - '**/*'
  base-directory: ./staging'
